###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Sofia",
    "reps": 100,
    "weight": 20,
    "unit":"kgs",
    "date":"10-2-2022"
}


###
GET http://localhost:3000/exercises HTTP/1.1

###
GET http://localhost:3000/exercises/637d321e0b31c98c6c732a4d

###
GET http://localhost:3000/exercises/?reps=20

###
GET http://localhost:3000/exercises/?weight=kgs


###
PUT http://localhost:3000/exercises/637d321e0b31c98c6c732a4d HTTP/1.1
content-type: application/json

{
    "name": "Umma",
    "reps": 2022,
    "weight": 20,
    "unit": "kgs",
    "date": "10-20-2022"
}

###
DELETE http://localhost:3000/exercises/637d321e0b31c98c6c732a4d HTTP/1.1


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Eternal Sunshine Of The Spotless Mind",
    "year": 2004,
    "language": "English"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "High Fidelity",
    "year": 2000,
    "language": "English"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Anchorman",
    "year": 2004,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "No Country For Old Men",
    "year": 2007,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "A Serious Man",
    "year": 2009,
    "language": "English"
}


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "City Of God",
    "year": 2003,
    "language": "Portuguese"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "title": "Parasite",
    "year": 2019,
    "language": "Korean"
}
